# Generated by Django 4.2.6 on 2023-10-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_userattendence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendence',
            name='status',
            field=models.CharField(max_length=45),
        ),
    ]
