# Generated by Django 4.2.6 on 2023-10-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_alter_userattendence_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userattendence',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='userattendence',
            name='status',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userattendence',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userattendence',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
