# Generated by Django 4.2.6 on 2023-10-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_userattendence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Shop_ATT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNo', models.IntegerField(blank=True, null=True)),
                ('AttTime', models.DateTimeField(blank=True, null=True)),
                ('attenStatus', models.BooleanField()),
                ('DeviceNo', models.CharField(max_length=600)),
                ('LockStatus', models.BooleanField()),
            ],
            options={
                'ordering': ['-AttTime'],
            },
        ),
    ]
