# Generated by Django 4.2.6 on 2023-10-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_rename_deviceno_tbl_shop_att_devicename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_shop_att',
            name='attenStatus',
            field=models.IntegerField(),
        ),
    ]
