# Generated by Django 4.2.6 on 2023-10-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_alter_tbl_shop_att_attenstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_Shop_ATT',
            new_name='damidata',
        ),
    ]
