# Generated by Django 4.2.6 on 2023-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_tbl_shop_att'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_shop_att',
            old_name='DeviceNo',
            new_name='DeviceName',
        ),
        migrations.RemoveField(
            model_name='tbl_shop_att',
            name='LockStatus',
        ),
        migrations.AddField(
            model_name='tbl_shop_att',
            name='DeviceIp',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
