# Generated by Django 4.2.6 on 2023-10-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_rename_tbl_shop_att_damidata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='damidata',
            new_name='tbl_Shop_ATT',
        ),
    ]
