# Generated by Django 4.2.6 on 2023-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_rename_damidata_tbl_shop_att'),
    ]

    operations = [
        migrations.CreateModel(
            name='dami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNo', models.IntegerField(blank=True, null=True)),
                ('AttTime', models.DateTimeField(blank=True, null=True)),
                ('attenStatus', models.IntegerField()),
                ('DeviceName', models.CharField(max_length=600)),
                ('DeviceIp', models.CharField(max_length=600, null=True)),
            ],
            options={
                'ordering': ['-AttTime'],
            },
        ),
    ]
