# Generated by Django 4.2.11 on 2026-06-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_dami'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRoll_payroll_deviceinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=255)),
                ('DeviceIp', models.CharField(max_length=100, unique=True)),
                ('Port', models.IntegerField(default=4370)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attendance Device',
                'verbose_name_plural': 'Attendance Devices',
                'db_table': 'PayRoll_payroll_deviceinfo',
            },
        ),
    ]
