# Generated by Django 4.2.11 on 2026-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_payroll_payroll_deviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('att_datetime', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_ip', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('reg_no', models.CharField(blank=True, max_length=100)),
                ('squad', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_attendance',
                'ordering': ['-att_datetime'],
            },
        ),
    ]
