# Generated by Django 4.2.11 on 2026-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_liveattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveattendance',
            name='slot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
